name: insulin_sync
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  android_intent_plus: ^5.3.0
  app_settings: ^5.2.0
  app_widget: ^0.4.0
  barcode_scan2: ^4.0.0
  cloud_firestore: ^5.4.4
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  davinci: ^2.5.1
  disable_battery_optimization: ^1.1.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_storage: ^12.4.5
  fl_chart: ^0.69.0
  floating_bottom_bar: ^0.0.3
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  flutter_barcode_scanner: ^2.0.0
  flutter_dotenv: ^5.2.1
  flutter_health_connect: ^1.2.3
  flutter_local_notifications: ^18.0.1
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^4.0.4
  home_widget: ^0.7.0+1
  html: ^0.15.5
  http: ^0.13.1
  image: ^3.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  mailer: ^6.4.1
  modal_progress_hud_nsn: ^0.5.1
  notification_permissions: ^0.6.1
  onnxruntime: ^1.4.1
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  store_redirect: ^2.0.2
  syncfusion_flutter_charts: 26.2.4
  tflite: ^1.1.2
  tflite_flutter: ^0.11.0
  tflite_flutter_helper_plus: ^0.0.2
  tflite_flutter_plus: ^0.0.1
  url_launcher: ^6.3.1

dev_dependencies:
  dcdg: any
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - images/logoicon.png
    - images/wheat.png
    - images/leg.png
    - images/lipid.png
    - images/barcode_scanner.png
    - images/salad.png
    - images/FSicon.png
    - images/LLUicon.png
    - images/circle-1.png
    - images/circle-2.png
    - images/circle-3.png
    - images/circle-4.png
    - images/circle-5.png
    - images/
    - images/insulinIcon.png
    - images/workoutIcon.png
    - images/mealIcon.png
    - images/plate.png
    - images/models/
    - images/vis_glucose.png
    - images/vis_ins.png
    - images/vis_food.png
    - images/vis_physical.png
    - images/vis_steps.png
